# Generated by Django 4.2.7 on 2023-11-08 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_area_table_githubaddmembertorepo_member_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area_table',
            name='userID',
        ),
        migrations.RemoveField(
            model_name='reactions_list',
            name='service',
        ),
        migrations.DeleteModel(
            name='Actions_list',
        ),
        migrations.DeleteModel(
            name='AREA_table',
        ),
        migrations.DeleteModel(
            name='Reactions_list',
        ),
        migrations.DeleteModel(
            name='Services_list',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
