# Generated by Django 4.2.7 on 2023-11-08 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_remove_area_table_userid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('token', models.CharField(max_length=255)),
                ('googleauth_id', models.CharField(blank=True, max_length=255, null=True)),
                ('Twitch_token', models.CharField(blank=True, max_length=255, null=True)),
                ('Spotify_token', models.CharField(blank=True, max_length=255, null=True)),
                ('Github_token', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reactions_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image_path', models.CharField(max_length=255)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions_list', to='authentication.services_list')),
            ],
        ),
        migrations.CreateModel(
            name='AREA_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActivated', models.BooleanField(verbose_name=False)),
                ('ActionService', models.CharField(max_length=25)),
                ('ReactionService', models.CharField(max_length=25)),
                ('ActionMethod', models.CharField(max_length=100)),
                ('ReactionMethod', models.CharField(max_length=100)),
                ('DiscordSendMessage_Body', models.TextField(blank=True)),
                ('OpenWeather_City', models.CharField(blank=True, max_length=200, null=True)),
                ('OpenWeather_Temp', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('OpenWeather_Humidity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('OpenWeather_airQuality', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('Github_RepositoryNameForAction', models.CharField(blank=True, max_length=200, null=True)),
                ('Github_OrganisationNameForAction', models.CharField(blank=True, max_length=200, null=True)),
                ('Github_RepositoryNameForReaction', models.CharField(blank=True, max_length=200, null=True)),
                ('Github_OrganisationNameForReaction', models.CharField(blank=True, max_length=200, null=True)),
                ('GithubAddMemberToRepo_Member', models.CharField(blank=True, max_length=200, null=True)),
                ('GithubAddMemberToRepo_Role', models.CharField(blank=True, max_length=200, null=True)),
                ('Google_SenderEmail', models.CharField(blank=True, max_length=255, null=True)),
                ('GoogleSendEmailTo_myEmail', models.CharField(blank=True, max_length=255, null=True)),
                ('GoogleSendEmailTo_ReceiverEmail', models.CharField(blank=True, max_length=255, null=True)),
                ('GoogleSendEmailTo_EmailBody', models.TextField(blank=True)),
                ('GoogleSendEmailTo_EmailObject', models.TextField(blank=True)),
                ('Spotify_PlaylistName', models.CharField(blank=True, max_length=50, null=True)),
                ('Spotify_SongUrl', models.CharField(blank=True, max_length=255, null=True)),
                ('SpotifyCreatePlaylist_PlaylistName', models.CharField(blank=True, max_length=255, null=True)),
                ('TimerEveryXSec_Interval', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('TimerAtTime_Time', models.CharField(blank=True, max_length=100, null=True)),
                ('TwitchStreamerIsLive_StreamerName', models.CharField(blank=True, max_length=100, null=True)),
                ('Twitch_UserPseudo', models.CharField(blank=True, max_length=100, null=True)),
                ('Twitch_ChanelName', models.CharField(blank=True, max_length=100, null=True)),
                ('userID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AREA', to='authentication.users')),
            ],
        ),
        migrations.CreateModel(
            name='Actions_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image_path', models.CharField(max_length=255)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_list', to='authentication.services_list')),
            ],
        ),
    ]
